In [2]:
# all the imports
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Newton's method for non - linear system of equations
# X(k+1) = X(k) - inv(J(k)) * F(X(k))
# J is jacobian matrix

# 2D
# f(x, y) = 0
# g(x, y) = 0
# solve for x and y

def f(X) :
    x = X[0]
    y = X[1]
    return x * x + x * y + y * y - 7
    
def g(X) :
    x = X[0]
    y = X[1]
    return x ** 3 + y ** 3 - 9

def fx(X) :
    x = X[0]
    y = X[1]
    return 2 * x + y
    
def fy(X) :
    x = X[0]
    y = X[1]
    return x + 2 * y
    
def gx(X) :
    x = X[0]
    y = X[1]
    return 3 * x * x

def gy(X) :
    x = X[0]
    y = X[1]
    return 3 * y * y
    
# initial approximation
x0 = 1.5
y0 = 0.5
X = [1.5, 0.5]
F = [f(X), g(X)]

num_iter = 20
for it in range(num_iter) :
    jacob = np.array([[fx(X), fy(X)], [gx(X), gy(X)]])
    inv_jacob = np.linalg.inv(jacob)
    nX = X - np.dot(inv_jacob, F)
    X = nX
    F = [f(X), g(X)]
    print(it + 1, X, F)

In [ ]:
# 3D

def f(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 10 * x + np.sin(x + y) - 1
    
def g(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 8 * y - np.cos(z - y) * np.cos(z - y) - 1

def h(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 12 * z + np.sin(z) - 1

def fx(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 10 + np.cos(x + y)
    
def fy(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return np.cos(x + y)

def fz(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 0
    
def gx(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 0

def gy(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 8 + 2 * np.cos(z - y) * np.sin(z - y) * -1

def gz(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 2 * np.cos(z - y) * np.sin(z - y)
    
def hx(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 0
    
def hy(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 0
    
def hz(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 12 + np.cos(z)
    
# initial approximation
X = [1/10, 1/4, 1/12]
F = [f(X), g(X), h(X)]

num_iter = 20
for it in range(num_iter) :
    jacob = np.array([[fx(X), fy(X), fz(X)], [gx(X), gy(X), gz(X)], [hx(X), hy(X), hz(X)]])
    inv_jacob = np.linalg.inv(jacob)
    nX = X - np.dot(inv_jacob, F)
    X = nX
    F = [f(X), g(X), h(X)]
    print(it + 1, X, F)

In [3]:
# 2D

def f(X) :
    x = X[0]
    y = X[1]
    return x * x + y * y - 1.12
    
def g(X) :
    x = X[0]
    y = X[1]
    return x * y - 0.23

def fx(X) :
    x = X[0]
    y = X[1]
    return 2 * x
    
def fy(X) :
    x = X[0]
    y = X[1]
    return 2 * y
    
def gx(X) :
    x = X[0]
    y = X[1]
    return y

def gy(X) :
    x = X[0]
    y = X[1]
    return x
    
    
X = [0.8, 0.23]
F = [f(X), g(X)]

num_iter = 20
for it in range(num_iter) :
    jacob = np.array([[fx(X), fy(X)], [gx(X), gy(X)]])
    inv_jacob = np.linalg.inv(jacob)
    print(inv_jacob)
    nX = X - np.dot(inv_jacob, F)
    X = nX
    F = [f(X), g(X)]
    print(it + 1, X, F)

[[ 0.68131494 -0.39175609]
 [-0.19587804  1.36262988]]
1 [1.07296883 0.20902146] [0.07495208114601892, -0.0057264871278215335]
[[ 0.48437876 -0.1887204 ]
 [-0.0943602   0.96875751]]
2 [1.03558293 0.22164153] [0.0015569717699643881, -0.0004718127204691447]
[[ 0.50599815 -0.21659338]
 [-0.10829669  1.0119963 ]]
3 [1.03469291 0.22228762] [1.2095583059590354e-06, -5.75028540422684e-07]
[[ 0.50661749 -0.21767772]
 [-0.10883886  1.01323499]]
4 [1.03469217 0.22228833] [1.0547118733938987e-12, -5.271338920920243e-13]
[[ 0.50661805 -0.21767881]
 [-0.10883941  1.0132361 ]]
5 [1.03469217 0.22228833] [0.0, 0.0]
[[ 0.50661805 -0.21767881]
 [-0.10883941  1.0132361 ]]
6 [1.03469217 0.22228833] [0.0, 0.0]
[[ 0.50661805 -0.21767881]
 [-0.10883941  1.0132361 ]]
7 [1.03469217 0.22228833] [0.0, 0.0]
[[ 0.50661805 -0.21767881]
 [-0.10883941  1.0132361 ]]
8 [1.03469217 0.22228833] [0.0, 0.0]
[[ 0.50661805 -0.21767881]
 [-0.10883941  1.0132361 ]]
9 [1.03469217 0.22228833] [0.0, 0.0]
[[ 0.50661805 -0.21767881

In [ ]:
# 3D

def f(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 10 * x + np.sin(x + y) - 1
    
def g(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 8 * y - np.cos(z - y) * np.cos(z - y) - 1

def h(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 12 * z + np.sin(z) - 1

def fx(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 10 + np.cos(x + y)
    
def fy(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return np.cos(x + y)

def fz(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 0
    
def gx(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 0

def gy(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 8 + 2 * np.cos(z - y) * np.sin(z - y) * -1

def gz(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 2 * np.cos(z - y) * np.sin(z - y)
    
def hx(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 0
    
def hy(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 0
    
def hz(X) :
    x = X[0]
    y = X[1]
    z = X[2]
    return 12 + np.cos(z)
    
X = [1/10, 1/4, 1/12]
F = [f(X), g(X), h(X)]

num_iter = 20
for it in range(num_iter) :
    jacob = np.array([[fx(X), fy(X), fz(X)], [gx(X), gy(X), gz(X)], [hx(X), hy(X), hz(X)]])
    inv_jacob = np.linalg.inv(jacob)
    nX = X - np.dot(inv_jacob, F)
    X = nX
    F = [f(X), g(X), h(X)]
    print(it + 1, X, F)